try{
    let a=10;
 console.log(aa);

} catch(err){
    console.log("Error in the code just check");
}